title: "BIXIRUN — витрина"
description: "Мобильное фитнес‑приложение на React Native/Expo: интервальные таймеры, тренировки, блог, магазин, Supabase."
remote_theme: just-the-docs/just-the-docs
color_scheme: light
logo: /assets/images/main_6_5.jpg
url: https://kr1zal.github.io
baseurl: /BIXIRUN-showcase

aux_links:
  GitHub Repo: https://github.com/kr1zal/BIXIRUN-showcase
  Live Demo: https://kr1zal.github.io/BIXIRUN-showcase/

nav_external_links:
  - title: Request code access
    url: https://github.com/kr1zal/BIXIRUN-showcase/issues/new?template=contact.yml

plugins:
  - jekyll-seo-tag

search_enabled: true
back_to_top: true
back_to_top_text: Наверх
