title: "BIXIRUN — витрина"
description: "Мобильное фитнес‑приложение на React Native/Expo: интервальные таймеры, тренировки, блог, магазин, Supabase."
url: https://kr1zal.github.io
baseurl: /BIXIRUN-showcase

# Чистая, сдержанная тема без фонов
remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Ensure custom head include is loaded by the theme
includes_dir: _includes
